frontend/controllers/PhotoController.php
<?php

class PhotoController extends FrontendController
{
	public $pageTitle = 'Phototag';

    public function accessRules()
    {
        return array_merge([
            [
                'deny',
                'actions' => ['upload', 'addTitle', 'delete', 'addTag', 'changeTag', 'all'],
                'users' => ['@'],
                'expression' => function (WebUser $user, CAccessRule $rule) {
                    return !$user->getIsAdmin();
                }
            ],
            [
                'allow',
                'users' => ['@'],
            ],
        ],
            parent::accessRules()
        );
    }

	public function actionIndex()
	{
		$rated_tags = ARTag::model()->getRatedTags( -1 );

		$max_frequency = 0;
		array_walk( $rated_tags, function( &$item ) use ( &$max_frequency )
			{
				if ( $item[ 'frequency' ] > 500 )
					$item[ 'frequency' ] = 500;
				if ( $max_frequency < $item[ 'frequency' ] )
					$max_frequency = $item[ 'frequency' ];
			}
		);

		$this->render( 'index', array( 'model' => new ARPhoto, 'rated_tags' => $rated_tags, 'max_frequency' => $max_frequency ) );
	}

	public function actionF( $uid )
	{
		$photo = ARPhoto::model()->findByAttributes( array(
			'uid' => $uid
		) );

		if ( !$photo ) {
			throw new CHttpException( 404, 'Запись не найдена' );
		}

		$this->render( 'view_full', array( 'photo' => $photo ) );
	}

	public function actionGroup( $uid, $page_size = 20 )
	{
		$pages = new CPagination( ARPhoto::model()->countByAttributes( array(
			'group_uid' => $uid
		) ) );
		$pages->pageSize = intval( $page_size );

        $all_photos = ARPhoto::model()->findAllByAttributes( array(
			'group_uid' => $uid
		) );

		$photos = array_slice( $all_photos, $pages->offset, $pages->limit );

        $all_photos = array_values(array_map(function (ARPhoto $item) {
            return [
                'uid' => $item->uid,
                'title' => $item->title,
                'tags' => $item->tags ? '#'.implode( ' #', $item->tags ) : '',
                'img_src' => Yii::app()->getBaseUrl().'/photos/original/'.$item->filename,
                'img_width' => $item->picture_width,
                'img_height' => $item->picture_height,
            ];
        }, $all_photos));

		$this->render( 'view_group', array( 'all_photos' => $all_photos, 'photos' => $photos, 'group_uid' => $uid, 'pages' => $pages ) );
	}

	public function actionSearch( $tags )
	{
		$all_photos = ARTag::model()->searchPhotosByTags( $tags );

		$pages = new CPagination( count( $all_photos ) );
		$pages->pageSize = intval( Yii::app()->request->getParam( 'page_size', 20 ) );

		$photos = array_slice( $all_photos, $pages->offset, $pages->limit );

        $all_photos = array_values(array_map(function (ARPhoto $item) {
            return [
                'uid' => $item->uid,
                'title' => $item->title,
                'tags' => $item->tags ? '#'.implode( ' #', $item->tags ) : '',
                'img_src' => Yii::app()->getBaseUrl().'/photos/original/'.$item->filename,
                'img_width' => $item->picture_width,
                'img_height' => $item->picture_height,
            ];
        }, $all_photos));

		$this->render( 'view_group', array( 'all_photos' => $all_photos, 'photos' => $photos, 'tags' => $tags, 'pages' => $pages ) );
	}

	public function actionAll( $page_size = 20 )
	{
		$pages = new CPagination( ARPhoto::model()->count() );
		$pages->pageSize = intval( $page_size );

        $all_photos = ARPhoto::model()->findAll();

        $photos = array_slice( $all_photos, $pages->offset, $pages->limit );

        $all_photos = array_values(array_map(function (ARPhoto $item) {
            return [
                'uid' => $item->uid,
                'title' => $item->title,
                'tags' => $item->tags ? '#'.implode( ' #', $item->tags ) : '',
                'img_src' => Yii::app()->getBaseUrl().'/photos/original/'.$item->filename,
                'img_width' => $item->picture_width,
                'img_height' => $item->picture_height,
            ];
        }, $all_photos));

		$this->render( 'view_group', array( 'all_photos' => $all_photos, 'photos' => $photos, 'pages' => $pages ) );
	}

	public function actionManageTags()
	{
		if ( Yii::app()->request->isPostRequest && Yii::app()->request->getParam( 'type' ) === 'download' )
		{
			$content = json_encode( ARTag::getTagMetadata(), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE );

			header( 'Content-Type: application/octet-stream' );
			header( 'Content-Description: File Transfer' );
			header( 'Content-Disposition: attachment; filename=phototag-tag-metadata-'.date( 'Y-m-d-H-i-s' ).'.txt' );
			header( 'Content-Transfer-Encoding: binary' );
			header( 'Expires: 0' );
			header( 'Cache-Control: must-revalidate' );
			header( 'Pragma: public' );
			header( 'Content-Length: ' . strlen( $content ) );

			print( $content );
			Yii::app()->end();
		}

		if ( Yii::app()->request->isPostRequest && Yii::app()->request->getParam( 'type' ) === 'upload' )
		{
			$file = CUploadedFile::getInstanceByName( 'metadata' );

			if ( !$file )
				throw new CHttpException( 400, 'Wheare iz de file?' );

			$data = json_decode( file_get_contents( CUploadedFile::getInstanceByName( 'metadata' )->getTempName() ) );

			if ( !isset( $data ) || gettype( $data ) !== 'array' )
				throw new CHttpException( 400, 'Bad JSON' );

			ARTag::setTagMetadata( $data );
			$this->redirect( array( 'photo/index' ) );
		}

		$this->render( 'manage_tags' );
	}

	// AJAX actions

	public function actionGetAllTags()
	{
		if ( !Yii::app()->request->isAjaxRequest )
			return $this->redirect( array( 'photo/index' ) );

		$criteria = new CDbCriteria;
		$criteria->order = 'group_name, group_order';

		$tags = ARTag::model()->findAll( $criteria );
		$tags = array_reduce( $tags, function( $carry, ARTag $tag ) { $carry[] = $tag->attributes; return $carry; }, array() );

		header( 'Content-Type: application/json' );
		print( CJSON::encode( $tags ) );
		Yii::app()->end();
	}

	public function actionSearchTags()
	{
		if ( !Yii::app()->request->isAjaxRequest )
			return $this->redirect( array( 'photo/index' ) );

		$part = Yii::app()->request->getParam( 'part' );

		if ( !isset( $part ) )
			throw new CHttpException( 400, 'Отсутствуют обязательные параметры' );

		$tags = ARTag::model()->searchTags( $part );
		$tags = array_reduce( $tags, function( $carry, $item ) { $carry[] = $item[ 'tag' ]; return $carry; }, array() );

		header( 'Content-Type: application/json' );
		print( CJSON::encode( $tags ) );
		Yii::app()->end();
	}

	public function actionAddTag( $uids )
	{
		if ( !Yii::app()->request->isAjaxRequest )
			return $this->redirect( array( 'photo/index' ) );

		$uids = explodeCommaSeparated( $uids );
		$tags = Yii::app()->request->getPost( 'tags' );

		if ( !isset( $tags ) )
			throw new CHttpException( 400, 'Отсутствуют обязательные параметры' );

		$affected = ARPhoto::model()->addTags( $tags, array(
			'uid' => $uids
		) );

		println( sprintf( 'Применено к %d записям', $affected ) );
		Yii::app()->end();
	}

	public function actionDelete( $uid )
	{
		if ( !Yii::app()->request->isAjaxRequest )
			return $this->redirect( array( 'photo/index' ) );

		$photo = ARPhoto::model()->findByAttributes( array(
			'uid' => $uid
		) );

		if ( !$photo ) {
			throw new CHttpException( 404, 'Запись не найдена' );
		}

		$affected = $photo->delete();

		println( sprintf( 'Применено: %s', $affected ? 'успешно' : 'неудача' ) );
		Yii::app()->end();
	}

	public function actionAddTitle( $uid )
	{
		if ( !Yii::app()->request->isAjaxRequest )
			return $this->redirect( array( 'photo/index' ) );

		$title = Yii::app()->request->getPost( 'title' );

		if ( !isset( $title ) )
			throw new CHttpException( 400, 'Отсутствуют обязательные параметры' );

		$photo = ARPhoto::model()->findByAttributes( array(
			'uid' => $uid
		) );

		if ( !$photo ) {
			throw new CHttpException( 404, 'Запись не найдена' );
		}

		$affected = $photo->addTitle( $title );

		println( sprintf( 'Применено: %s', $affected ? 'успешно' : 'неудача' ) );
		Yii::app()->end();
	}

	public function actionChangeTag( $uids )
	{
		if ( !Yii::app()->request->isAjaxRequest )
			return $this->redirect( array( 'photo/index' ) );

		$uids = explodeCommaSeparated( $uids );
		$tags = Yii::app()->request->getPost( 'tags' );

		if ( !isset( $tags ) )
			throw new CHttpException( 400, 'Отсутствуют обязательные параметры' );

		$affected = ARPhoto::model()->updateTags( $tags, array(
			'uid' => $uids
		) );

		println( sprintf( 'Применено к %d записям', $affected ) );
		Yii::app()->end();
	}

	// upload

	public function actionUpload()
	{
		if ( Yii::app()->request->isPostRequest )
		{
			$files = CUploadedFile::getInstances( ARPhoto::model(), 'files' );

			$group_uid = UidGeneratorBehavior::makeUid();

			foreach ( $files as $file )
				ARPhoto::createFromUploadedFile( $file, $group_uid );

			$this->redirect( array( 'photo/group', 'uid' => $group_uid ) );
		}

		$this->render( 'upload', array( 'model' => new ARPhoto ) );
	}
}

;

frontend/controllers/SiteController.php
<?php

class SiteController extends FrontendController
{
	public $pageTitle = 'Welcome to Phototag';

	public function init()
	{
		parent::init();

		$this->breadcrumbs = array(
			$this->pageTitle => array( 'index' ),
		);
	}

	public function accessRules()
	{
		return array_merge(
			array(
				array( 'allow',
					/*'actions' => array('error')*/ ),
			),
			parent::accessRules()
		);
	}

	public function actionIndex()
	{
		$this->render( 'index' );
	}

	public function actionLogin()
	{
		$model = new LoginForm;

		if ( Yii::app()->request->isAjaxRequest )
		{
			echo CActiveForm::validate( $model );
			Yii::app()->end();
		}

		if ( Yii::app()->request->isPostRequest )
		{
			$model->attributes = $_POST[ 'LoginForm' ];

			if ( $model->validate() && $model->login() )
				$this->redirect( Yii::app()->user->returnUrl );
		}

		$this->render( 'login', array( 'model' => $model ) );
	}

	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect( array( Yii::app()->defaultController.'/index' ) );
	}

	public function actionError()
	{
		if ( $error = Yii::app()->errorHandler->error )
		{
			if ( Yii::app()->request->isAjaxRequest )
				echo $error[ 'message' ]; // TODO
			else
				$this->render( 'error', $error );
		}
	}
}

;

frontend/views/controllers/photo/index.php
<?php $this->widget( 'TagSearch' ); ?>

<div class="tag-cloud">
	<?php
	shuffle($rated_tags);
	foreach ( $rated_tags as $item )
	{
		$font_size = round( $item[ 'frequency' ] / $max_frequency * 40 + 10 );
		echo CHtml::link( '#'.$item[ 'tag' ].PHP_EOL, array( 'photo/search', 'tags' => $item[ 'tag' ] ), array( 'class' => 'tag-cloud-item', 'style' => 'font-size: '.$font_size.'px' ) );
	}
	?>
</div>

frontend/views/controllers/photo/manage_tags.php
<div class="form" style="margin-top: 50px;">
	<?php
	echo CHtml::beginForm();
	echo CHtml::hiddenField( 'type', 'download' );
	echo CHtml::submitButton( 'Скачать информацию о тегах' );
	echo CHtml::endForm();
	?>
</div>
<div class="form" style="margin-top: 50px;">
	<?php
	echo CHtml::beginForm( '', 'POST', array( 'enctype' => 'multipart/form-data' ) );
	echo CHtml::hiddenField( 'type', 'upload' );
	echo CHtml::fileField( 'metadata' );
	echo CHtml::submitButton( 'Загрузить информацию о тегах' );
	echo CHtml::endForm();
	?>
</div>

frontend/views/controllers/photo/upload.php
<div class="form">
	<?php $form = $this->beginWidget( 'CActiveForm', array
	(
		'enableAjaxValidation' => true,
		'enableClientValidation' => true,
		'htmlOptions' => array
		(
			'action' => 'photo/upload',
			'enctype' => 'multipart/form-data'
		)

	) ); ?>

	<?php echo $form->errorSummary( $model ); ?>

	<fieldset style="margin-top: 30px; margin-bottom: 30px;">
		<div><?php echo $form->fileField( $model, 'files[]', array( 'multiple' => 'multiple' ) ); ?></div>
	</fieldset>

	<div>
		<?php echo CHtml::submitButton( 'Загрузить фотографии', array( 'class' => 'btn btn-primary btn-lg' ) ); ?>
	</div>

	<?php $this->endWidget(); ?>
</div>

frontend/views/controllers/photo/view_full.php
<?php

echo CHtml::image(
	Yii::app()->getBaseUrl( true ).'/photos/original/'.$photo->filename,
	$photo->title ? $photo->title : 'Без названия',
	array( 'class' => '' ) );

frontend/views/controllers/photo/view_group.php
<?php //$this->widget( 'EditableTags', array( 'tags' => '', 'ajax_url' => array( 'photo/changeTag', 'group_uid' => $group_uid ) ) ); ?>
<?php $this->widget( 'TagSearch', array( 'tags' => isset( $tags ) ? $tags : '' ) ); ?>

<?php if ( Yii::app()->user->isAdmin ): ?>
<div class="sidebar"><div class="add-tag-button inline-block glyphicon glyphicon-plus btn btn-primary btn-lg"></div></div>
<?php endif; ?>

<?php
/** @var CPagination $pages */

$photos_on_page = count( $photos );
/** @var CClientScript $cs */
$cs = Yii::app()->clientScript;
$cs->registerScript('all-photos', sprintf('var all_photos = %s;', json_encode($all_photos)), CClientScript::POS_BEGIN);
$cs->registerScript('all-photos-count', sprintf('var all_photos_count = %d;', count($all_photos)), CClientScript::POS_BEGIN);
$cs->registerScript('current-photo-number', 'var current_photo_number = null;', CClientScript::POS_BEGIN);
?>

<div class="info-header">
	<span>Найдено <?php echo isset( $pages ) ? $pages->itemCount : $photos_on_page; ?> фотографий</span>
	<?php if ( Yii::app()->user->isAdmin ): ?>
		<a class="select-all-link">Выделить все</a>
		<a class="select-none-link">Снять выделение</a>
	<?php endif; ?>
</div>

<div class="add-tag-dialog display-none">
<?php
echo CHtml::tag( 'div', array( 'class' => 'add-tag-dialog-form' ),
	CHtml::beginForm( array( 'photo/addTag' ) ).
	CHtml::tag( 'div', array(),
		CHtml::textField( 'tags', '', array( 'class' => 'add-tag-dialog-input tag-autocomplete', 'placeholder' => 'Введите теги' ) ).
		CHtml::tag( 'div', array( 'class' => 'add-tag-dialog-submit inline-block glyphicon glyphicon-ok btn btn-primary btn-lg' ), '' ).
//		CHtml::ajaxSubmitButton( 'Сохранить', array( 'photo/addTag', 'group_uid' => $group_uid ), array( 'success' => 'function() { window.location.reload(); }' ), array( 'class' => 'hidden' ) )
		CHtml::submitButton( 'Сохранить', array( 'class' => 'hidden' ) ).
		CHtml::tag( 'div', array( 'class' => 'select-tags-button glyphicon glyphicon-th-list btn btn-primary btn-lg' ), '' )
	).
	CHtml::endForm()
);
?>
</div>

<div class="add-title-dialog display-none">
	<?php
	echo CHtml::tag( 'div', array( 'class' => 'add-title-dialog-form' ),
		CHtml::beginForm( array( 'photo/addTitle' ) ).
		CHtml::tag( 'div', array(),
			CHtml::textField( 'title', '', array( 'class' => 'add-title-dialog-input', 'placeholder' => 'Введите описание' ) ).
			CHtml::tag( 'div', array( 'class' => 'add-title-dialog-submit inline-block glyphicon glyphicon-ok btn btn-primary btn-lg' ), '' ).
//		CHtml::ajaxSubmitButton( 'Сохранить', array( 'photo/addTitle', 'group_uid' => $group_uid ), array( 'success' => 'function() { window.location.reload(); }' ), array( 'class' => 'hidden' ) )
			CHtml::submitButton( 'Сохранить', array( 'class' => 'hidden' ) )
		).
		CHtml::endForm()
	);
	?>
</div>

<div class="full-photo-dialog display-none">
	<div class="full-photo-dialog-img"></div>
	<div class="full-photo-dialog-title"></div>
	<div class="full-photo-dialog-tags"></div>
	<div class="full-photo-dialog-controls">
		<a class="inline-block glyphicon glyphicon-chevron-left full-photo-dialog-prev"></a>
		<a class="inline-block glyphicon glyphicon-chevron-right full-photo-dialog-next"></a>
	</div>
</div>

<div style="margin-bottom: 20px"></div>

<?php
	$paging_url = array( $this->id . '/' . $this->action->id );
	foreach ( $_GET as $key => $value )
		$paging_url[ $key ] = $value;
	unset( $paging_url[ 'page_size' ] );
	unset( $paging_url[ 'page' ] );
?>

<?php if ( isset( $pages ) ): ?>
	<div>Показывать по:
		<?php echo CHtml::link( '10', CMap::mergeArray( $paging_url, array( 'page_size' => 10, 'page' => 1 ) ) ); ?> |
		<?php echo CHtml::link( '20', CMap::mergeArray( $paging_url, array( 'page_size' => 20, 'page' => 1 ) ) ); ?> |
		<?php echo CHtml::link( '50', CMap::mergeArray( $paging_url, array( 'page_size' => 50, 'page' => 1 ) ) ); ?> |
        <?php echo CHtml::link( '100', CMap::mergeArray( $paging_url, array( 'page_size' => 100, 'page' => 1 ) ) ); ?> |
        <?php echo CHtml::link( '500', CMap::mergeArray( $paging_url, array( 'page_size' => 500, 'page' => 1 ) ) ); ?>
	</div>
	<div>
		<?php
		echo CHtml::beginForm( $paging_url, 'GET' );
		echo CHtml::tag( 'span', array(), 'Перейти на страницу: ' );
		echo CHtml::hiddenField( 'page_size', $pages->pageSize );
		echo CHtml::textField( 'page', '', array( 'style' => 'width: 50px' ) );
		echo CHtml::submitButton( 'Go', array( 'name' => null ) );
		echo CHtml::endForm();
		?>
	</div>
<?php endif; ?>

<?php if ( isset( $pages ) ): ?>
	<div class="link-pager-block">
		<?php $this->widget( 'CLinkPager', array(
			'htmlOptions' => array(
				'class' => 'link-pager',
			),
			'header' => 'Страницы: ',
			'firstPageLabel' => 'первая',
			'lastPageLabel' => 'последняя',
			'nextPageLabel' => 'вперед',
			'prevPageLabel' => 'назад',
			'pages' => $pages

		) ); ?>
	</div>
<?php endif; ?>

<div class="photo-thumbnails <?php echo !Yii::app()->user->isAdmin ? '' : 'selectable-photo-thumbnails'; ?>" data-total-photos="<?php echo $photos_on_page; ?>">
<?php for ( $current_photo_number = 0; $current_photo_number < $photos_on_page; $current_photo_number++ ):
	$photo = $photos[ $current_photo_number ]; ?>
	<?php
		$max_width = 360;

		if ( $photo->picture_width * 360 < $photo->picture_height * 480 )
			$max_width = round( $photo->picture_width * 220 / $photo->picture_height + 60 );
	?>
	<div class="photo-thumbnail" data-photo-uid="<?php echo $photo->uid; ?>" style="max-width: <?php echo $max_width.'px'; ?>;">
		<div class="photo-thumbnail-links">
			<div style="inline-block">
			<?php echo CHtml::link( '', array( 'photo/f/'.$photo->uid ), array(
				'class' => 'open-photo-link glyphicon glyphicon-zoom-in',
				'data-current-number' => $pages->pageSize * $pages->currentPage + $current_photo_number,
			) ); ?>
			<?php echo !Yii::app()->user->isAdmin ? '' : CHtml::link( '', '', array(
				'class' => 'add-title-link glyphicon glyphicon-font',
			) ); ?>
			<?php echo !Yii::app()->user->isAdmin ? '' : CHtml::link( '', '', array(
				'class' => 'delete-photo-link glyphicon glyphicon-trash',
			) ); ?>
			</div>
		</div>
		<div class="photo-thumbnail-image selectable-item">
			<?php echo CHtml::image(
				Yii::app()->getBaseUrl().'/photos/thumbnails/'.$photo->thumbnail_filename,
				$photo->title ? $photo->title : 'Без названия',
				array(
					'class' => !Yii::app()->user->isAdmin ? 'open-photo-link cursor-pointer' : '',
                    'data-current-number' => $pages->pageSize * $pages->currentPage + $current_photo_number,
				) ); ?>
		</div>
		<?php echo CHtml::tag( 'div', array( 'class' => 'photo-thumbnail-title' ), $photo->title ); ?>
		<?php if ( Yii::app()->user->isAdmin ) { ?>
			<?php $this->widget( 'EditableTags', array( 'tags' => !empty( $photo->tags ) ? '#'.implode( ' #', $photo->tags ) : '', 'ajax_url' => array( 'photo/changeTag', 'uids' => $photo->uid ) ) ); ?>
		<?php } else { ?>
			<?php echo CHtml::tag( 'div', array( 'class' => 'photo-thumbnail-tags' ), '#'.implode( ' #', $photo->tags ) ); ?>
		<?php } ?>
	</div>
<?php endfor; ?>
</div>

<div style="margin-bottom: 20px"></div>

<?php if ( isset( $pages ) ): ?>
	<div>Показывать по:
		<?php echo CHtml::link( '10', CMap::mergeArray( $paging_url, array( 'page_size' => 10, 'page' => 1 ) ) ); ?> |
		<?php echo CHtml::link( '20', CMap::mergeArray( $paging_url, array( 'page_size' => 20, 'page' => 1 ) ) ); ?> |
		<?php echo CHtml::link( '50', CMap::mergeArray( $paging_url, array( 'page_size' => 50, 'page' => 1 ) ) ); ?> |
        <?php echo CHtml::link( '100', CMap::mergeArray( $paging_url, array( 'page_size' => 100, 'page' => 1 ) ) ); ?> |
        <?php echo CHtml::link( '500', CMap::mergeArray( $paging_url, array( 'page_size' => 500, 'page' => 1 ) ) ); ?>
	</div>
	<div>
		<?php
		echo CHtml::beginForm( $paging_url, 'GET' );
		echo CHtml::tag( 'span', array(), 'Перейти на страницу: ' );
		echo CHtml::hiddenField( 'page_size', $pages->pageSize );
		echo CHtml::textField( 'page', '', array( 'style' => 'width: 50px' ) );
		echo CHtml::submitButton( 'Go', array( 'name' => null ) );
		echo CHtml::endForm();
		?>
	</div>
<?php endif; ?>

<?php if ( isset( $pages ) ): ?>
	<div class="link-pager-block">
		<?php $this->widget( 'CLinkPager', array(
			'htmlOptions' => array(
				'class' => 'link-pager',
			),
			'header' => 'Страницы: ',
			'firstPageLabel' => 'первая',
			'lastPageLabel' => 'последняя',
			'nextPageLabel' => 'вперед',
			'prevPageLabel' => 'назад',
			'pages' => $pages

		) ); ?>
	</div>
<?php endif; ?>